name: "release"

on:
  push:
    branches:
      - "main"

jobs:
  pre-release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16.17.0
          registry-url: https://registry.npmjs.org/
      - run: yarn install
      - run: yarn build:pack

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: "Build"
          files: |
            *.tgz
